---
name: Validate Template

on:
  push:
    branches:
      - main
      - master

  pull_request:
    branches:
      - main
      - master

jobs:
  lint:
    runs-on: ubuntu-latest
    name: Validate Template

    steps:
      # We checkout all of the dependencies and subcomponents to test them together
      - name: Checkout Code
        uses: actions/checkout@v5
        with:
          submodules: recursive
          token: ${{ secrets.PAT_TOKEN }}
          path: fastapi

      - name: Checkout Base
        uses: actions/checkout@v5
        with:
          repository: datarobot/af-component-base
          token: ${{ secrets.PAT_TOKEN }}
          path: base

      - name: Checkout Sqlite
        uses: actions/checkout@v5
        with:
          repository: datarobot/af-component-fastapi-backend-persistence-sqlite
          token: ${{ secrets.PAT_TOKEN }}
          submodules: recursive
          path: sqlite
          ref: damon/oauth-refactor  # TODO: Change this back when approved 

      - name: Checkout Oauth
        uses: actions/checkout@v5
        with:
          repository: datarobot/af-component-fastapi-backend-oauth
          token: ${{ secrets.PAT_TOKEN }}
          submodules: recursive
          path: oauth
          ref: damon/oauth-refactor # TODO: Remove before done
  

      - name: Setup Python & uv
        uses: astral-sh/setup-uv@v5
        with:
          python-version: "3.11"

      - name: Install Task
        uses: go-task/setup-task@v1

      - name: Install Copier
        run: |
          uv tool install --with copier_template_extensions copier
          uv tool install ruff
          uv tool install isort
          uv tool install mypy

      - name: Install go
        uses: actions/setup-go@v5
      
      # Put this before copier as our template runs yamlfmt
      - name: Install yamlfmt
        run: go install github.com/google/yamlfmt/cmd/yamlfmt@latest

      # The rm git here is because copier tries and fails to pull submoduels otherwise
      - name: Generate Test Project
        run: |
          rm -rf base/.git fastapi/.git sqlite/.git oauth/.git
          rm fastapi/.gitmodules sqlite/.gitmodules oauth/.gitmodules
          copier copy base mytemplate --defaults --trust --data 'include_core=true'
          copier copy fastapi mytemplate --defaults --trust
          copier copy sqlite mytemplate --defaults --trust
          copier copy oauth mytemplate --defaults --trust
      
      - name: Check lint
        run: |
          cd mytemplate/web
          task lint-check

      - name: Run yamlfmt
        run: yamlfmt -conf fastapi/.yamlfmt.yaml -gitignore_exclude -gitignore_path mytemplate/.gitignore -lint mytemplate