---
name: Validate Template

on:
  push:
    branches:
      - main
      - master

  pull_request:
    branches:
      - main
      - master

jobs:
  lint:
    runs-on: ubuntu-latest
    name: Validate Template

    steps:
      - name: Checkout Code
        uses: actions/checkout@v5
        with:
          submodules: recursive
          token: ${{ secrets.PAT_TOKEN }}

      - name: Setup Python & uv
        uses: astral-sh/setup-uv@v5
        with:
          python-version: "3.11"

      - name: Install Copier
        run: |
          uv tool install copier
          uv tool install ruff
          uv tool install isort

      - name: Generate Test Project
        run: |
          git config credential.helper \
            '!f() { echo username=${GITHUB_ACTOR}; echo "password=$GIT_TOKEN"; };f
          copier copy . mytemplate --defaults --trust
        env:
          GIT_TOKEN: ${{ secrets.PAT_TOKEN }}
          GITHUB_ACTOR: ${{ github.actor }}

      - name: Install go
        uses: actions/setup-go@v5
      - name: Install yamlfmt
        run: go install github.com/google/yamlfmt/cmd/yamlfmt@latest

      - name: Run yamlfmt
        run: yamlfmt -conf .yamlfmt.yaml -lint ./mytemplate
