---
name: Validate Template

on:
  push:
    branches:
      - main
      - master

  pull_request:
    branches:
      - main
      - master

jobs:
  lint:
    runs-on: ubuntu-latest
    name: Validate Template

    steps:
      - name: Checkout Code
        uses: actions/checkout@v5
        with:
          submodules: recursive
          token: ${{ secrets.PAT_TOKEN }}

      - name: Setup Python & uv
        uses: astral-sh/setup-uv@v5
        with:
          python-version: "3.11"

      - name: Install Copier
        run: |
          uv tool install --with copier_template_extensions copier
          uv tool install ruff
          uv tool install isort

      - name: Install go
        uses: actions/setup-go@v5
      
      # Put this before copier as our template runs yamlfmt
      - name: Install yamlfmt
        run: go install github.com/google/yamlfmt/cmd/yamlfmt@latest

      # The rm git here is because copier tries to 
      - name: Generate Test Project
        run: |
          rm -rf .git/
          rm .gitmodules
          copier copy . mytemplate --defaults --trust

      - name: Run yamlfmt
        run: yamlfmt -conf .yamlfmt.yaml -lint ./mytemplate
